# Generated by Django 3.2.6 on 2021-09-23 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='', max_length=50)),
                ('text', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=30)),
                ('place', models.CharField(default='', max_length=30)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('age', models.IntegerField(default=False)),
                ('space_characteristics', models.CharField(default='', max_length=150)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('date_archived', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('event_can_create', 'Can create event'), ('event_edit', 'Can edit event'), ('event_can_archive', 'Can archive event'), ('event_can_delete', 'Can delete evetn')],
            },
        ),
        migrations.CreateModel(
            name='EventDeleteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
