# Generated by Django 3.2.7 on 2021-09-14 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='', max_length=50)),
                ('text', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=30)),
                ('place', models.CharField(default='', max_length=30)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('age', models.IntegerField(default=False)),
                ('space_characteristics', models.CharField(default='', max_length=150)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(default='', max_length=30)),
                ('archive', models.CharField(default='N', max_length=1)),
                ('delete', models.CharField(default='N', max_length=1)),
            ],
        ),
    ]
