# Generated by Django 3.2.7 on 2021-09-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_name',
        ),
    ]
