# Generated by Django 3.2.6 on 2021-09-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'permissions': [('event_can_create', 'Can create event'), ('event_edit', 'Can edit event'), ('event_can_archive', 'Can archive event'), ('event_can_delete', 'Can delete event')]},
        ),
    ]
