# Generated by Django 3.2.7 on 2021-09-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_events_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='events',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
