# Generated by Django 3.2.6 on 2021-09-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='events',
            name='type',
        ),
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.ManyToManyField(to='events.CategoryEvents', verbose_name='kategorija'),
        ),
    ]
