# Generated by Django 3.2.7 on 2021-09-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210926_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryevents',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoryevents',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoryevents',
            name='valid_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='categoryevents',
            name='valid_to',
            field=models.DateField(null=True),
        ),
    ]
