# Generated by Django 3.2.7 on 2021-09-13 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210913_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_name',
            new_name='event_name',
        ),
        migrations.AddField(
            model_name='events',
            name='age',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='events',
            name='archive',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='events',
            name='author',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='events',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='events',
            name='delete',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='events',
            name='expiration_date',
            field=models.DateTimeField(default=''),
        ),
        migrations.AddField(
            model_name='events',
            name='place',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='events',
            name='space_characteristics',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.DateTimeField(default=''),
        ),
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
