# Generated by Django 3.2.7 on 2021-09-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210930_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=False)),
                ('valid_from', models.DateField(null=True)),
                ('valid_to', models.DateField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('valid_from', models.DateField(null=True)),
                ('valid_to', models.DateField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='events',
            name='age',
        ),
        migrations.RemoveField(
            model_name='events',
            name='space_characteristics',
        ),
        migrations.AddField(
            model_name='events',
            name='age',
            field=models.ManyToManyField(to='events.Age', verbose_name='starosna doba posetilaca'),
        ),
        migrations.AddField(
            model_name='events',
            name='space_characteristics',
            field=models.ManyToManyField(to='events.SpaceCharacteristics', verbose_name='karakteristike prostora'),
        ),
    ]
