# Generated by Django 3.2.7 on 2021-09-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_events_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='name',
            new_name='event_name',
        ),
    ]
