# Generated by Django 3.2.7 on 2021-10-04 21:24

from django.db import migrations


def load_spacecharacteristics (apps, schema_editor):
    SpaceCharacteristics = apps.get_model ('events', 'SpaceCharacteristics')
    spacecharacteristics_accessibility = SpaceCharacteristics (name='Prilagodjeno za invalide', valid_from='2021-10-01', valid_to='2022-10-01', approved=True, status=True)
    spacecharacteristics_accessibility.save()
    spacecharacteristics_pets = SpaceCharacteristics (name='Pet-frendli', valid_from='2021-10-01', valid_to='2022-10-01', approved=True, status=True)
    spacecharacteristics_pets.save()
    spacecharacteristics_parking = SpaceCharacteristics (name='Besplatan parking', valid_from='2021-10-01', valid_to='2022-10-01', approved=True, status=True)
    spacecharacteristics_parking.save()


def delete_spacecharacteristics(apps, schema_editor):
    SpaceCharacteristics = apps.get_model("events", "SpaceCharacteristics")
    SpaceCharacteristics.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_age_name'),
    ]

    operations = [
        migrations.RunPython(load_spacecharacteristics, delete_spacecharacteristics),
    ]
