# Generated by Django 3.2.6 on 2021-09-12 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Category',
        ),
        migrations.AddField(
            model_name='article',
            name='your_choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.category'),
            preserve_default=False,
        ),
    ]
