# Generated by Django 3.2.6 on 2021-09-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210912_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='your_choice',
        ),
        migrations.AddField(
            model_name='article',
            name='Category',
            field=models.ManyToManyField(to='news.Category', verbose_name='Kategorija'),
        ),
    ]
