# Generated by Django 3.2.7 on 2021-09-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210912_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='valid_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='valid_to',
            field=models.DateField(null=True),
        ),
    ]
