# Generated by Django 3.2.6 on 2021-09-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pitanje')),
                ('option_one', models.CharField(max_length=30, verbose_name='Prva opcija')),
                ('option_two', models.CharField(max_length=30, verbose_name='Druga opcija')),
                ('option_three', models.CharField(max_length=30, verbose_name='Treca opcija')),
                ('option_one_count', models.IntegerField(default=0)),
                ('option_two_count', models.IntegerField(default=0)),
                ('option_three_count', models.IntegerField(default=0)),
            ],
        ),
    ]
