# Generated by Django 3.2.7 on 2021-10-06 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pitanje')),
                ('option_one', models.CharField(max_length=30, verbose_name='Prva opcija')),
                ('option_two', models.CharField(max_length=30, verbose_name='Druga opcija')),
                ('option_three', models.CharField(max_length=30, verbose_name='Treca opcija')),
                ('option_one_count', models.IntegerField(default=0)),
                ('option_two_count', models.IntegerField(default=0)),
                ('option_three_count', models.IntegerField(default=0)),
                ('public', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('poll_can_create', 'Can create poll')],
            },
        ),
    ]
