# Generated by Django 3.2.7 on 2021-10-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Rezultati ankete su javni'),
        ),
    ]
