# Generated by Django 3.2.6 on 2021-10-12 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='voter',
            field=models.ManyToManyField(related_name='voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
