# Generated by Django 3.2.6 on 2021-10-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_voter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'permissions': [('poll_can_create', 'Can create poll'), ('poll_edit', 'Can edit poll'), ('poll_can_archive', 'Can archive poll'), ('poll_can_delete', 'Can delete poll')]},
        ),
    ]
