# Generated by Django 3.2.7 on 2021-09-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_choice_choice_choice_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='load_date',
            new_name='pub_date',
        ),
    ]
