# Generated by Django 3.2.7 on 2021-09-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210917_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='option',
        ),
        migrations.AddField(
            model_name='choice',
            name='option_1',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='option_2',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='option_3',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
