# Generated by Django 3.2.7 on 2021-10-04 18:14

from django.db import migrations
from openpyxl import load_workbook


def load_streetaddress (apps, schema_editor):
    StreetAddress = apps.get_model ('registration', 'StreetAddress')
    wb1 = load_workbook ('media/codebook_excel/Sifarnik_ulica.xlsx')
    ws = wb1.active
    for row in ws.values:
        streetaddress_name = row[0]
        if streetaddress_name is not None:
            streetaddress = StreetAddress (name = streetaddress_name, valid_from='2021-10-01', valid_to='2022-10-01', approved=True, status=True)
            streetaddress.save()


def delete_streetaddress(apps, schema_editor):
    StreetAddress = apps.get_model('registration', 'StreetAddress')
    StreetAddress.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_city_migration'),
    ]

    operations = [
        migrations.RunPython(load_streetaddress, delete_streetaddress)
    ]
