# Generated by Django 3.2.6 on 2021-09-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articledeletionrequest',
            name='Article',
        ),
        migrations.RemoveField(
            model_name='articledeletionrequest',
            name='User',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleDeletionRequest',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
