# Generated by Django 3.2.6 on 2021-10-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutus'),
        ('home', '0003_contact'),
    ]

    operations = [
    ]
