# Generated by Django 3.2.6 on 2021-10-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_merge_0003_aboutus_0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
