# Generated by Django 3.2.7 on 2021-10-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverts',
            name='description',
            field=models.TextField(verbose_name='Opis oglasa'),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='expire_date',
            field=models.DateField(verbose_name='Datum isticanja oglasa'),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='load_date',
            field=models.DateField(verbose_name='Datum postavljanja oglasa'),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Naslov'),
        ),
    ]
